name: Command Executor

on:
  push:
    paths:
      - 'command-executor/**'
    branches: 
      -  'main'
  workflow_dispatch:
  
env: 
  AZURE_WEBAPP_NAME: CommandExecutor
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: command-executor
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: command-executor/package-lock.json

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.COMMAND_EXECUTOR_AZURE_CREDENTIALS }}
    
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.COMMAND_EXECUTOR_AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./command-executor/
